socorro/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('socorro_app.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socorro_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='socorro_app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('principal_157/', views.man, name='main'),
    path('cads/', views.cads, name='cads'),
    path('castrado/', views.cadastrar, name='cadas'),
    path('<int:id_usu>inicio/', views.inicio, name='inicio'),
    path('<int:id_usu>n157<int:valida>/new/', views.novo_trabalho, name='novo'),
    path('<int:id_usu>/c157/<int:valida>/new/', views.novo_curso, name='novo_curso'),
    path('<int:id_usu>/m157/<int:valida>/new/', views.novo_materia, name='novo_materia'),
    path('<int:id_usu>cmi157<int:valida>/princ/', views.select_ini, name='processar_curso_ini'),
    path('<int:id_usu>cma157<int:valida>/princ/', views.select_add, name='processar_curso'),
    path('<int:id_usu>upload/', views.coletar_arquivo, name='upload_trabalho'),
    path('<int:id_usu>pronto/<int:trabalho>', views.coletar_arquivo_pronto, name='upload_trabalho_pronto'),
    path('<int:id_usu>/<int:trabalho>aceito/', views.aceitar_trabalho, name='aceito'),
    path('<int:id_usu>/<int:trabalho>compra/', views.tela_compra, name='tela_compra'),
    path('<int:id_usu>/<int:trabalho>entrega/', views.recebe_pg, name='entrega'),
    path('<int:id_usu>perfil/', views.perfil_usu, name='perfil'),
]

socorro_app/models.py
from django.db import models

class Usuario(models.Model):    
    id_usuario = models.AutoField(primary_key=True)
    nome = models.TextField(max_length=255)
    cell = models.IntegerField()
    saldo = models.IntegerField()
    chave_pix = models.CharField(max_length=200)
    gmail = models.EmailField(max_length=500)
    senha = models.CharField(max_length=100)
    Trabalhos_aceitos = models.CharField(max_length=100)
    Trabalhos_feitos = models.CharField(max_length=100)

class Cursos_class(models.Model):
    cursos = models.CharField(max_length=200)

    def __str__(self):
        return self.cursos

class Materias_class(models.Model):
    pai = models.ForeignKey(Cursos_class, on_delete=models.CASCADE)
    materias = models.CharField(max_length=200)

    def __str__(self):
        return self.materias

class Trabalhos_fazer(models.Model):
    curso_trab = models.ForeignKey(Cursos_class, on_delete=models.CASCADE)
    fazer_materia = models.ForeignKey(Materias_class, on_delete=models.CASCADE)
    trabalho = models.CharField(max_length=200)
    trabalho_cm_pronto = models.FileField(upload_to='pronto/')
    quem_pediu_fazer = models.CharField(max_length=200)
    quem_fez = models.FloatField()
    quem_pago=models.CharField(max_length=1000)
    data = models.CharField(max_length=100)
    valor_afazer = models.FloatField()
    pago = models.FloatField()

class TrabalhoArquivo(models.Model):
    trabalho = models.ForeignKey(Trabalhos_fazer, related_name='arquivos', on_delete=models.CASCADE)
    arquivo = models.FileField(upload_to='uploads/')

class Transacao(models.Model):
    qual_trabalho = models.ForeignKey(Trabalhos_fazer, on_delete=models.CASCADE)
    quem_compro = models.CharField(max_length=200)
    quem_vendeu = models.CharField(max_length=200)
    valor_pago = models.FloatField()

socorro_app/forms.py
from django import forms
from .models import *

class TrabalhoForm(forms.ModelForm):
    class Meta:
        model = Trabalhos_fazer
        fields = ['curso_trab', 'fazer_materia', 'trabalho', 'trabalho_cm_pronto', 'quem_pediu_fazer','quem_fez', 'data', 'valor_afazer', 'pago']

class TrabalhoArquivoForm(forms.ModelForm):
    class Meta:
        model = TrabalhoArquivo
        fields = ['arquivo']

socorro_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import JsonResponse
from .models import *
from .forms import *
import crcmod
import qrcode

def index(request):
    return render(request, 'socorro_app/login.html',{"validacao":0})

def cads(request):
    return render(request, 'socorro_app/cadastro.html')
def inicio(request,id_usu):
    cursos= Cursos_class.objects.all()
    materias=Materias_class.objects.all()
    trabalhos = Trabalhos_fazer.objects.all()
    usuario = Usuario.objects.filter(id_usuario=id_usu)
    return render(request, 'socorro_app/inicio.html',{"usu":usuario,"curso":cursos,"materias":materias,'trabalhos': trabalhos})

def perfil_usu(request, id_usu):
    usu = Usuario.objects.get(id_usuario=id_usu)
    trabalhos_ids = [int(id.strip()) for id in usu.Trabalhos_aceitos.split(',') if id.strip().isdigit()]
    trabalhos = Trabalhos_fazer.objects.filter(id__in=trabalhos_ids)
    trabalhos_ = [int(id.strip()) for id in usu.Trabalhos_feitos.split(',') if id.strip().isdigit()]
    trabalho_f = Trabalhos_fazer.objects.filter(id__in=trabalhos_)
    return render(request, 'socorro_app/perfil.html',{"usu":usu,"trabalhos":trabalhos,"feitos":trabalho_f})

def cadastrar(request):
    if request.method == 'POST':
        nome = request.POST.get('nome')
        gmail = request.POST.get('email')
        senha = request.POST.get('senha')
        tell = request.POST.get('celular')
        pix = request.POST.get('pix')

        if Usuario.objects.filter(nome=nome).exists() or Usuario.objects.filter(gmail=gmail).exists():
            return render(request, 'socorro_app/cadastro.html',{"validacao":1,"sms":"Usuario já Esta cadastrado"})
        else:
            novo_usuario = Usuario(nome=nome, gmail=gmail, senha=senha,cell=tell,chave_pix=pix,saldo=0)
            novo_usuario.save()
            return render(request,'socorro_app/login.html',{"validacao":1,"sms":"Novo usuario cadastrado com sucesso!"})
        
def man(request):
    if request.method == 'POST':
        gmail = request.POST.get('email')
        senha = request.POST.get('senha')
        usuario = Usuario.objects.filter(gmail=gmail)
        cursos= Cursos_class.objects.all()
        materias=Materias_class.objects.all()
        trabalhos = Trabalhos_fazer.objects.all()
        if Usuario.objects.filter(gmail=gmail,senha=senha).exists():
            return render(request, 'socorro_app/inicio.html',{"usu":usuario,"curso":cursos,"materias":materias,'trabalhos': trabalhos})
        else:
            return render(request,'socorro_app/login.html',{"validacao":1,"sms":"Senha incorreta ou usuário não cadastrado!"})
        
def novo_trabalho(request,id_usu,valida):
    usuario = Usuario.objects.get(id_usuario=id_usu)
    cursos= Cursos_class.objects.all()
    materias=Materias_class.objects.all()
    return render(request, 'socorro_app/novo_trabalho.html',{"usu":usuario,"curso":cursos,"materias":materias,"validacao":valida})

def novo_curso(request, id_usu, valida):
    usuario = Usuario.objects.get(id_usuario=id_usu)
    cursos = Cursos_class.objects.all()
    materias = Materias_class.objects.all()
    
    if request.method == 'POST':
        curso_nome = request.POST.get('curso')
        if not Cursos_class.objects.filter(cursos=curso_nome).exists():
            novo_curso = Cursos_class(cursos=curso_nome)
            novo_curso.save()
        return redirect('socorro_app:novo_curso', id_usu=id_usu, valida=9)
    
    return render(request, 'socorro_app/novo_trabalho.html', {"usu": usuario, "curso": cursos, "materias": materias, "validacao": valida})

def novo_materia(request, id_usu, valida):
    usuario = Usuario.objects.get(id_usuario=id_usu)
    cursos = Cursos_class.objects.all()
    materias = Materias_class.objects.all()
    
    if request.method == "POST":
        curso_id = request.POST.get('curso')
        materia_nome = request.POST.get('mate')
        curso = Cursos_class.objects.get(id=curso_id)
        
        if not Materias_class.objects.filter(pai=curso, materias=materia_nome).exists():
            nova_materia = Materias_class(pai=curso, materias=materia_nome)
            nova_materia.save()
        return redirect('socorro_app:novo_materia', id_usu=id_usu, valida=9)
    
    return render(request, 'socorro_app/novo_trabalho.html', {"usu": usuario, "curso": cursos, "materias": materias, "validacao": valida})


def select_ini(request, id_usu, valida):
    usuario = Usuario.objects.filter(id_usuario=id_usu)
    cursos = list(Cursos_class.objects.all())
    materias_cujo = []
    pai = None
    if request.method == 'POST':
        curso_id = request.POST.get('curso_id')
        if curso_id:
            pai = get_object_or_404(Cursos_class, id=curso_id)
            materias_cujo = Materias_class.objects.filter(pai=pai)
            cursos.remove(pai)
            cursos.insert(0, pai)
            for materia in materias_cujo:
                print(materia.materias)
    
    trabalhos = Trabalhos_fazer.objects.filter(curso_trab=curso_id)
    return render(request, 'socorro_app/inicio.html', {"usu": usuario,"curso": cursos,"materias": materias_cujo,"validacao": valida,'trabalhos': trabalhos})

def select_add(request, id_usu, valida):
    usuario = Usuario.objects.get(id_usuario=id_usu)
    cursos = list(Cursos_class.objects.all())
    materias_cujo = []
    pai = None
    if request.method == 'POST':
        curso_id = request.POST.get('curso_id')
        if curso_id:
            pai = get_object_or_404(Cursos_class, id=curso_id)
            materias_cujo = Materias_class.objects.filter(pai=pai)
            cursos.remove(pai)
            cursos.insert(0, pai)
            for materia in materias_cujo:
                print(materia.materias)
    return render(request, 'socorro_app/novo_trabalho.html', {"usu": usuario,"curso": cursos,"materias": materias_cujo,"validacao": valida})

def coletar_arquivo(request, id_usu):
    if request.method == 'POST':
        curso_id = request.POST.get('curso_trab')
        materia_id = request.POST.get('Materia_traba')
        data = request.POST.get('data')
        title = request.POST.get('trabalho')
        valor = request.POST.get('valor_afazer')
        arquivos = request.FILES.get('arquivos')
        curso = get_object_or_404(Cursos_class, id=curso_id)
        materia = get_object_or_404(Materias_class, id=materia_id)
        trabalho = Trabalhos_fazer.objects.create(
                curso_trab=curso,
                fazer_materia=materia,
                trabalho=title,
                trabalho_cm_pronto='pendente', 
                quem_pediu_fazer=id_usu,
                quem_fez=0,
                data=data,
                valor_afazer=valor,
                pago=0
            )
        TrabalhoArquivo.objects.create(trabalho=trabalho, arquivo=arquivos)
        trabalhos = Trabalhos_fazer.objects.all()
        usuario = Usuario.objects.filter(id_usuario=id_usu)
        cursos= Cursos_class.objects.all()
        materias=Materias_class.objects.all()
        return render(request, 'socorro_app/inicio.html',{"usu":usuario,"curso":cursos,"materias":materias,'trabalhos': trabalhos})

def aceitar_trabalho(request, id_usu,trabalho):
    usu = get_object_or_404(Usuario, id_usuario=id_usu)
    trabalhuuu = get_object_or_404(Trabalhos_fazer, id=trabalho)
    if usu.Trabalhos_aceitos:
        trabalhos_aceitos_list = usu.Trabalhos_aceitos.split(',')
    else:
        trabalhos_aceitos_list = []
    if str(trabalho) not in trabalhos_aceitos_list:
        trabalhos_aceitos_list.append(str(trabalho))
        usu.Trabalhos_aceitos = ','.join(trabalhos_aceitos_list)
        usu.save()
    trabalhuuu.quem_fez=id_usu
    trabalhuuu.save()

    trabalho_ids = [int(id) for id in trabalhos_aceitos_list]
    trabalhos = Trabalhos_fazer.objects.filter(id__in=trabalho_ids)
    
    trabalhos_ = [int(id.strip()) for id in usu.Trabalhos_feitos.split(',') if id.strip().isdigit()]
    trabalho_f = Trabalhos_fazer.objects.filter(id__in=trabalhos_)
    valor=Trabalhos_fazer.objects.get(id=trabalho)
    return render(request, 'socorro_app/perfil.html',{"usu":usu,"trabalhos":trabalhos,"feitos":trabalho_f,"valor":valor.valor_afazer})

def recebe_pg(request, id_usu,trabalho):
    usu = Usuario.objects.get(id_usuario=id_usu)
    trabalhos_ids = [int(id.strip()) for id in usu.Trabalhos_aceitos.split(',') if id.strip().isdigit()]
    trabalhos = Trabalhos_fazer.objects.filter(id__in=trabalhos_ids)
    trabalhos_ = [int(id.strip()) for id in usu.Trabalhos_feitos.split(',') if id.strip().isdigit()]
    trabalho_f = Trabalhos_fazer.objects.filter(id__in=trabalhos_)
    valor=Trabalhos_fazer.objects.get(id=trabalho)
    return render(request, 'socorro_app/perfil.html',{"usu":usu,"trabalhos":trabalhos,"validacao":trabalho,"feitos":trabalho_f,"valor":valor.valor_afazer})

def coletar_arquivo_pronto(request, id_usu,trabalho):
    if request.method == 'POST':
        valor = request.POST.get('valor_novo')
        arquivos = request.FILES.get('arquivos')
        tra_fazer=Trabalhos_fazer.objects.get(id=trabalho)
        tra_fazer.pago=valor
        tra_fazer.trabalho_cm_pronto=arquivos
        tra_fazer.save()
        usuario = Usuario.objects.get(id_usuario=id_usu)
        trabalhos_a = usuario.Trabalhos_aceitos.split(',')
        trabalhos_a.remove(str(trabalho))
        usuario.Trabalhos_aceitos = ','.join(trabalhos_a)
        feitos = usuario.Trabalhos_feitos.split(',')
        feitos.append(str(trabalho)) 
        usuario.Trabalhos_feitos = ','.join(feitos)
        usuario.save()
        usuario = Usuario.objects.filter(id_usuario=id_usu)
        cursos = Cursos_class.objects.all()
        materias = Materias_class.objects.all()
        trabalhos = Trabalhos_fazer.objects.all()
        return render(request, 'socorro_app/inicio.html',{"usu":usuario,"curso":cursos,"materias":materias,'trabalhos': trabalhos})

def tela_compra(request, id_usu,trabalho):
    trabalhos=Trabalhos_fazer.objects.filter(id=trabalho)

socorro_app/templates/socorro_app/inicio.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Socorro-157</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_2 .css' %}">
    <link rel="icon" href="{% static 'imgs/sos .png' %}" type="image/x-icon">
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="project-idea">
                <h1>Socorro - Plataforma para negociação de trabalhos</h1>
                <p>Uma solução inovadora para ensino e aprendizado.</p>
            </div>
            <div class="user-profile">
                <p>Bem-vindo, {{ usu.0.nome }}</p>
                <a href="{% url 'socorro_app:perfil' id_usu=usu.0.id_usuario %}">➔</a>
            </div>
        </div>

        <div class="content">
            <section class="how-it-works">
                <h2>Como Funciona</h2>
                <ul>
                    <li>Você pode pagar para alguém fazer seu trabalho.</li>
                    <li>Você pode receber para fazer trabalhos de outras pessoas.</li>
                    <li>Tudo muito simples...</li>
                    <li>Sem contar que não é necessário expor seu nome.</li>
                </ul>
            </section>

            <div class="search-filter">
                <label for="comboCursos">Curso:</label>
                <select id="comboCursos" onchange="enviarCursoSelecionado()">
                    {% for cur in curso %}
                    <option value="{{ cur.id }}">{{ cur.cursos }}</option>
                    {% endfor %}
                </select>
                
                <label for="comboMaterias">Matéria:</label>
                <select id="comboMaterias">
                    {% for mate in materias %}
                    <option value="{{ mate.id }}">{{ mate.materias }}</option>
                    {% endfor %}
                </select>
                <form action="{% url 'socorro_app:inicio' id_usu=usu.0.id_usuario %}">
                    <button type="submit">Inicio</button>
                </form>
                {% for usuario in usu %}
                <form action="{% url 'socorro_app:novo' id_usu=usuario.id_usuario valida=0 %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Adicionar novo trabalho</button>
                </form>
                {% endfor %}
            </div>
            
            {% for trabalho in trabalhos %}
            <div class="image-list">
                <div class="image-item">
                    <div class="image-details">
                        <h2>{{ trabalho.trabalho }}</h2>
                        <p>Curso: {{ trabalho.curso_trab.cursos }}</p>
                        <p>Matéria: {{ trabalho.fazer_materia.materias }}</p>
                        <p>Data de Entrega: {{ trabalho.data }}</p>
                        {% if trabalho.trabalho_cm_pronto != "pendente"%}
                        <p>Valor : R$ {{ trabalho.pago }}</p>
                        <h3 style="color: green;">Trabalho pronto</h3>
                        <form action="{% url 'socorro_app:tela_compra' id_usu=usu.0.id_usuario trabalho=trabalho.id %}" method="get">
                            <button type="submit" style="background-color: red;">Comprar Trabalho</button>
                        </form>
                        {% endif %}
                        {% if trabalho.trabalho_cm_pronto == "pendente"%}
                        <p>Valor disposto a pagar: R$ {{ trabalho.valor_afazer }}</p>
                        {% if trabalho.quem_fez > 0 %}
                        <h3>Alguem ja esta fazendo...</h3>
                        {% endif %}
                        {% if trabalho.quem_fez == 0 %}
                            </div>
                            <form action="{% url 'socorro_app:aceito' id_usu=usu.0.id_usuario trabalho=trabalho.id %}" method="get">
                                <button type="submit">Fazer trabalho</button>
                            </form>
                            {% endif %}
                            {% endif %}
                            {% for arquivo in trabalho.arquivos.all %}
                            <a href="{{ arquivo.arquivo.url }}" target="_blank">Visualizar</a>
                            {% endfor %}
                    </div>
                </div>
                {% endfor %}
        </div>
        
        <div class="footer">
            <p>&copy; 2024 Socorro - Plataforma para negociação de trabalhos. Todos os direitos reservados.</p>
        </div>
    </div>
    
<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    function enviarCursoSelecionado() {
        var comboCursos = document.getElementById('comboCursos');
        var cursoSelecionado = comboCursos.value;
        var url = "{% url 'socorro_app:processar_curso_ini' id_usu=usu.0.id_usuario valida=0 %}";
        var csrftoken = getCookie('csrftoken');

        var xhr = new XMLHttpRequest();
        xhr.open('POST', url, true);
        xhr.setRequestHeader('X-CSRFToken', csrftoken);

        var formData = new FormData();
        formData.append('curso_id', cursoSelecionado);

        xhr.onload = function () {
            if (xhr.status >= 200 && xhr.status < 400) {
                var response = xhr.responseText;
                console.log(response);
                document.open();
                document.write(response);
                document.close();
            } else {
                console.error('Erro na resposta do servidor:', xhr.responseText);
            }
        };

        xhr.onerror = function () {
            console.error('Erro na requisição AJAX.');
        };

        xhr.send(formData);
    }
</script>
</body>
</html>

socorro_app/templates/socorro_app/login.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Socorro-login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_1.css' %}">
    <link rel="icon" href="{% static 'imgs/sos .png' %}" type="image/x-icon">
</head>

<body>
  <div class="center-container">
    <div class="welcome-message">
      <h2>Bem-vindo... talvez possamos te ajudar</h2>
  </div>
            <div class="frame">
                <div class="center-text">
                    <h1>Tela login</h1>
                    <form action="{% url 'socorro_app:main' %}" method="post">
                        {% csrf_token %}
                        <label for="username">E-mail Cadastrado:</label>
                        <input type="text" id="username" name="email" required>
                        <label for="password">Senha:</label>
                        <input type="password" id="password" name="senha" required>
                        <button class="staio_button" type="submit">Entrar</button>
                    </form>
                    <form action="{% url 'socorro_app:cads' %}" method="post">
                        {% csrf_token %}
                        <button class="staio_button" type="submit">Cadastrar</button>
                    </form>
                </div>
            </div>
        </div>
    {% if validacao > 0 %}
    <div id="welcomeModal" class="modal" style="display:block;">
        <div class="modal-content">
            <span class="close">&times;</span>
            <p>{{ sms }}</p>
        </div>
    </div>
    {% endif %}

    <script src="{% static 'scripts/login_cads.js' %}"></script>
</body>
</html>

socorro_app/templates/socorro_app/novo_trabalho.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Socorro-Novo</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_3.css' %}">
    <link rel="icon" href="{% static 'imgs/sos .png' %}" type="image/x-icon">
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="project-idea">
                <h1>Socorro - Área de inserção de trabalhos</h1>
                <form action="{% url 'socorro_app:inicio' id_usu=usu.id_usuario %}">
                    <button type="submit">Inicio</button>
                </form>
            </div>
            <div class="user-profile">
                <p>Vamos lá {{ usu.nome }}</p>
                <a href="{% url 'socorro_app:perfil' id_usu=usu.id_usuario %}" style="color: white;">➔</a>
            </div>
        </div>

        <div class="content">
            <section class="how-it-works">
                <h2>Como Funciona:</h2>
                <ul>
                    <li>Você deve selecionar primeiramente o curso e a área do seu trabalho.</li>
                    <li>Caso não tenha no sistema, você pode adicioná-la.</li>
                    <li>Logo após, você pode inserir o trabalho no formato que estiver (pdf, png, etc.).</li>
                    <li>A estimativa de valores ficará a cargo do avaliador.</li>
                    <li>Caso queira uma aula sobre o assunto, selecione os cards (Valor adicional).</li>
                </ul>
            </section>
        </div>
        
        <form action="{% url 'socorro_app:upload_trabalho' id_usu=usu.id_usuario %}" method="post" enctype="multipart/form-data" class="form-upload-trabalho">
            {% csrf_token %}
            <div class="search-filter">
                <label for="comboCursos">Curso:</label>
                <select id="comboCursos" name="curso_trab" onchange="enviarCursoSelecionado()">
                    {% for cur in curso %}
                    <option value="{{ cur.id }}">{{ cur.cursos }}</option>
                    {% endfor %}
                </select>
                <button type="button" onclick="abrirModalCurso()">+</button>
        
                <label for="comboMaterias">Matéria:</label>
                <select id="comboMaterias" name="Materia_traba">
                    {% for mate in materias %}
                    <option value="{{ mate.id }}">{{ mate.materias }}</option>
                    {% endfor %}
                </select>
                <button type="button" onclick="abrirModalMateria()">+</button>
            </div>
        
            <div class="form-group">
                <label for="Titulo">Título:</label>
                <input type="text" id="Titulo" name="trabalho" required>
            </div>
        
            <div class="form-group">
                <label for="valor">Valor a pagar (máx):</label>
                <input type="number" id="valor" name="valor_afazer" required>
            </div>
        
            <div class="form-group">
                <label for="data">Data:</label>
                <input type="date" id="data" name="data" required>
            </div>
        
            <div class="form-group">
                <label for="Arquivos">Arquivos do trabalho:</label>
                <input type="file" id="Arquivos" name="arquivos" required>
            </div>
            
            <button type="submit" class="submit-button">Enviar</button>
        </form>
        
    </div>

    <div id="modalCurso" class="modal">
        <div class="modal-content">
            <span class="close" onclick="fecharModal('modalCurso')">&times;</span>
            <form action="{% url 'socorro_app:novo_curso' id_usu=usu.id_usuario valida=9 %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="curso_v">Curso:</label>
                    <input type="text" id="curso_v" name="curso" required>
                </div>
                <button type="submit">Adicionar</button>
            </form>
        </div>
    </div>

    <div id="modalMateria" class="modal">
        <div class="modal-content">
            <span class="close" onclick="fecharModal('modalMateria')">&times;</span>
            <form action="{% url 'socorro_app:novo_materia' id_usu=usu.id_usuario valida=9 %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="comboCursos">Curso:</label>
                    <select id="comboCursos" name="curso">
                        {% for cur in curso %}
                        <option value="{{ cur.id }}">{{ cur.cursos }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="Materia">Matéria:</label>
                    <input type="text" id="Materia" name="mate" required>
                </div>
                <button type="submit">Adicionar</button>
            </form>
        </div>
    </div>

    <script src="{% static 'scripts/login_cads.js' %}"></script>
    
    <script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    function enviarCursoSelecionado() {
        var comboCursos = document.getElementById('comboCursos');
        var cursoSelecionado = comboCursos.value;
        var url = "{% url 'socorro_app:processar_curso' id_usu=usu.id_usuario valida=0 %}";
        var csrftoken = getCookie('csrftoken');

        var xhr = new XMLHttpRequest();
        xhr.open('POST', url, true);
        xhr.setRequestHeader('X-CSRFToken', csrftoken);

        var formData = new FormData();
        formData.append('curso_id', cursoSelecionado);

        xhr.onload = function () {
            if (xhr.status >= 200 && xhr.status < 400) {
                var response = xhr.responseText;
                console.log(response);
                document.open();
                document.write(response);
                document.close();
            } else {
                console.error('Erro na resposta do servidor:', xhr.responseText);
            }
        };

        xhr.onerror = function () {
            console.error('Erro na requisição AJAX.');
        };

        xhr.send(formData);
    }

    function abrirModalCurso() {
        document.getElementById('modalCurso').style.display = 'block';
    }

    function abrirModalMateria() {
        document.getElementById('modalMateria').style.display = 'block';
    }

    function fecharModal(modalId) {
        document.getElementById(modalId).style.display = 'none';
    }
    </script>
</body>
</html>

socorro_app/templates/socorro_app/voto_tst.html
<h2>Avaliar {{ trabalho.trabalho }}</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Enviar Avaliação</button>
</form>